title: Fundatillus
tagline: Grounded in reason. Illuminated by wonder.
author: Adam Clements
email: adam@fundatillus.com
description: >-
  The personalish site of Adam Clements — nerd, thinker, seeker.
  Grounded in reason. Open to the extraordinary.

baseurl: ""
url: "https://fundatillus.com"

github_username: fundatillus
linkedin_username: clementsjoshua

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  style: compressed

permalink: /blog/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .DS_Store
  - LICENSE
  - README.md
